apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcart
spec:
  replicas: 2 # Adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: devcart
  template:
    metadata:
      labels:
        app: devcart
    spec:
      containers:
        - name: devcart-frontend
          image: skyhunter93/devcart-frontend:latest
          envFrom:
            - configMapRef:
                name: devcart-configmap
        - name: devcart-backend
          image: skyhunter93/devcart-backend:latest
          envFrom:
            - configMapRef:
                name: devcart-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: service-devcart
spec:
  selector:
    app: devcart
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer # Use LoadBalancer for cloud providers that support it, or NodePort for testing
