version: '3'
services:
  front:
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    image: frontend-image:latest
    container_name: frontend-container
    env_file: .env
    networks:
      - mern-stack-network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    image: backend-image:latest
    env_file: .env
    container_name: backend-container
    networks:
      - mern-stack-network
    volumes:
      - ./express-docker:/app
networks:
  mern-stack-network:




